# Generated by Django 3.2.4 on 2021-06-13 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('sex', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=355, null=True)),
                ('headpic', models.TextField(null=True)),
                ('role_id', models.UUIDField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_by', models.CharField(max_length=255)),
                ('update_by', models.CharField(max_length=255)),
            ],
        ),
    ]
